name: DevSecOps Security Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build VAmPI Docker image
        run: docker build -t vampi:latest .

      - name: Run VAmPI container
        run: docker compose up -d

      - name: Wait for service to be ready
        run: sleep 10

      - name: Run Trivy on image
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vampi:latest'
          format: 'sarif'
          output: 'trivy.sarif'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

      - name: Run Semgrep manually
        continue-on-error: true
        run: |
          docker run --rm \
            -v $(pwd):/src \
            returntocorp/semgrep \
            semgrep ci --config p/default --sarif --output semgrep.sarif

      - name: Upload Semgrep SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - name: Run ZAP Baseline Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy zap-baseline.py \
            -t http://localhost:5002 \
            -r zap-report.html \
            -x zap-report.xml \
            -J zap-report.json


      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            zap-report.*
